[tool.poetry]
name = "plexplaylistmanager"
version = "0.1.0"
description = ""
authors = ["0xChloe <chloe@catastrophesoftware.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
PlexAPI = "^4.15.11"
spotipy = "^2.23.0"
httpx = "^0.27.0"
rtoml = "^0.10.0"
Flask = "^3.0.3"
Bootstrap-Flask = "^2.4.0"
flask-admin = "^1.6.1"
flask-executor = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
plexplaylistmanager = 'plexplaylistmanager.__init__:create_app'