[tool.poetry]
name = "plex-playlist-manager"
version = "0.1.0"
description = ""
authors = ["0xChloe <chloe@catastrophesoftware.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
PlexAPI = "^4.15.9"
spotipy = "^2.23.0"
rtoml = "^0.10.0"
schedule = "^1.2.1"
requests = "^2.31.0"
flask = "^3.0.2"
bootstrap-flask = "^2.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
